version: '3.7'
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: taxiDB
    ports:
      - 5432:5432

  scheduler:
    image: uber-scheduler:latest
    ports:
      - 8080:8080
    environment:
      - UBER_CLID= #input your clid
      - UBER_APIKEY= #input your apiKey
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/taxiDB
      - SPRING_DATASOURCE_USERNAME=pguser
      - SPRING_DATASOURCE_PASSWORD=pgpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin